//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BC.Auth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Authorization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Authorization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BC.Auth.Resources.Authorization", typeof(Authorization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application details cannot be found in the database..
        /// </summary>
        public static string APP_DETAILS_NOT_FOUND_IN_DB {
            get {
                return ResourceManager.GetString("APP_DETAILS_NOT_FOUND_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified grant type is not supported.
        /// </summary>
        public static string GRANT_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("GRANT_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OpenID Connect request cannot be retrieved..
        /// </summary>
        public static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token is no longer valid..
        /// </summary>
        public static string TOKEN_LONGER_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_LONGER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive user consent is required..
        /// </summary>
        public static string USER_CONSENT_REQUIRED {
            get {
                return ResourceManager.GetString("USER_CONSENT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logged in user is not allowed to access this client application..
        /// </summary>
        public static string USER_NOT_ALLOWED_TO_APP {
            get {
                return ResourceManager.GetString("USER_NOT_ALLOWED_TO_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The user is no longer allowed to sign in..
        /// </summary>
        public static string USER_NOT_ALLOWED_TO_SIGNIN {
            get {
                return ResourceManager.GetString("USER_NOT_ALLOWED_TO_SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not logged in..
        /// </summary>
        public static string USER_NOT_LOGGED {
            get {
                return ResourceManager.GetString("USER_NOT_LOGGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user details cannot be retrieved..
        /// </summary>
        public static string USER_WITHOUT_DETAILS {
            get {
                return ResourceManager.GetString("USER_WITHOUT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details concerning the calling client application cannot be found..
        /// </summary>
        public static string WITHOUT_CLIENT_APP_DETAILS {
            get {
                return ResourceManager.GetString("WITHOUT_CLIENT_APP_DETAILS", resourceCulture);
            }
        }
    }
}
